config/routes.rb
Rails.application.routes.draw do
  resources :foods

end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :calorie, :protein, :carbohydrate, :lipid, :eat_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.haml
= simple_form_for(@food) do |f|
  = f.error_notification

  .field
    = f.input :name, :input_html => { :class => 'form-control' }, label: "名称", placeholder: "食べたものを入力"
  .field
    = f.input :calorie, :input_html => { :class => 'form-control' }, label: "カロリー", placeholder: "カロリー（kcal）"
  .field
    = f.input :protein, :input_html => { :class => 'form-control' }, label: "タンパク質", placeholder: "タンパク質（g）"
  .field
    = f.input :carbohydrate, :input_html => { :class => 'form-control' }, label: "炭水化物", placeholder: "炭水化物（g）"
  .field
    = f.input :lipid, :input_html => { :class => 'form-control' }, label: "脂質", placeholder: "脂質（g）"
  .field
    = f.input :eat_day, label: "日付"

  .field
    = f.button :submit

app/views/foods/edit.html.haml
%h1 Editing food

= render 'form'

= link_to 'Show', @food
\|
= link_to 'Back', foods_path

app/views/foods/index.html.haml
%h1 Listing foods

%table
  %thead
    %tr
      %th Name
      %th Calorie
      %th Protein
      %th Carbohydrate
      %th Lipid
      %th Eat day
      %th
      %th
      %th

  %tbody
    - @foods.each do |food|
      %tr
        %td= food.name
        %td= food.calorie
        %td= food.protein
        %td= food.carbohydrate
        %td= food.lipid
        %td= food.eat_day
        %td= link_to 'Show', food
        %td= link_to 'Edit', edit_food_path(food)
        %td= link_to 'Destroy', food, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Food', new_food_path

app/views/foods/new.html.haml
.food-form-container.col-md-10.col-md-offset-1
  %h3 食べたものを登録

  = render 'form'

  = link_to '戻る', foods_path

app/views/foods/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @food.name
%p
  %b Calorie:
  = @food.calorie
%p
  %b Protein:
  = @food.protein
%p
  %b Carbohydrate:
  = @food.carbohydrate
%p
  %b Lipid:
  = @food.lipid
%p
  %b Eat day:
  = @food.eat_day

= link_to 'Edit', edit_food_path(@food)
\|
= link_to 'Back', foods_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{ name: "viewport", content: "width=device-width,initial-scale=1" }
    %title MacroDiet
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / bootstrap
    %link{ rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", integrity: "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", crossorigin: "anonymous" }
    %link{ rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css", integrity: "sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp", crossorigin: "anonymous" }
    %script{ src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js", integrity: "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", crossorigin: "anonymous" }
  %body
    = yield